#
# CSE183 Assignment 8 Backend
#
# some comments

openapi: '3.0.3'

info:
  description: CSE183 Assignment 8 Backend
  version: 0.1.0
  title: CSE183 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /channels:
    get:
      description: Get messages from channel
      parameters:
        - in: query
          name: channel
          schema:
            type: string
          required: false
          description: Name of channel
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllChannels'
        404:
          description: Channel not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /channels/{channel}:
    post:
      description: Send New Message
      parameters:
        - in: path
          name: channel
          schema:
            type: string
          required: true
          description: Name of channel
        - in: query
          name: thread
          schema:
            type: string
          required: false
      requestBody:
        description: New Message Content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessage'
      responses:
        201:
          description: EMail Response
        400:
          description: Mailbox not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    AllChannels:
      type: array
      items:
        $ref: '#/components/schemas/ChannelResponse'

    ChannelResponse:
      type: object
      properties:
        message:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    NewMessage:
      type: object
      properties:
        content:
          type: string

    Message:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        from:
          type: string
        to:
          type: string
        sent-at:
          type: string
        thread:
          type: array

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

security:
  - bearerAuth: []         # use the same name as above